name: Go deploy

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.24.1]
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
      - name: Install Dependecies
        run: go get .
      - name: Test 
        run: go test ./test -json > TestResults-go.json
      - name: Upload Go test TestResults
        uses: actions/upload-artifact@v4
        with:
          name: Go-Test-Results 
          path: TesteResults-go.json
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
      
